name: Deploy Next.js App

on:
  push:
    branches: [ main ]  # Trigger on pushes to the "main" branch (adjust as needed)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specify the runner OS

    steps:
      - uses: actions/checkout@v3  # Checkout code from your repository

      - name: Use Node.js 16  # Adjust Node.js version if needed
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install  # Or yarn install, depending on your project

      - name: Build the Next.js app
        run: npm run build  # Or yarn build

      - name: Deploy to GitHub Pages (using your PAT)
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: ./next  # Adjust path based on your build output directory

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages@v4.3.0  # Action to deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use PAT stored as secret
          branch: gh-pages  # Target branch for deployment (adjust if needed)
          publish_dir: ${{ secrets.ARTIFACT_NAME }}  # Artifact name from previous step
